### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by vinilnarayan** [pankyopkey/pCloudy-sample-projects#50]
I have tried to execute a mobile app with '**pCloudy-sample-projects/Wdio/Chapter5-WDIO+AndroidOnParallelDevice/**'

And getting error like below.

**>pCloudy-sample-projects-master/mine/forMobileAppAndriod
> wdio wdio.android.parallel.conf.js

Execution of 1 spec files started at 2020-07-09T03:29:55.894Z

<<< NATIVE APP TESTS STARTED >>>
[0-0] FAILED
<<< TEST FINISHED >>>

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:00 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FORMOBILEAPPANDROID@1.0.0 test: `wdio wdio.android.parallel.conf.js`
npm ERR! Exit status 1
npm ERR!**

**Comment by shibupanda** [comment]
@vinilnarayan 
Could you please provide the complete logs for it. 
You can reach support@pcloudy.com for quick fix. Feel free to re open if issue still exists.
